select * from customer limit 20;

-- q1. what is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Which gender has a higher average order value?
SELECT gender,
       COUNT(*) AS total_customers,
       ROUND(AVG(purchase_amount::numeric),2) AS avg_purchase_amount
FROM customer
GROUP BY gender
ORDER BY avg_purchase_amount DESC;

--Find the top 3 categories by total revenue, but only include categories where more than 50 purchases were made.
SELECT category, 
       COUNT(purchase_amount) AS purchases, 
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
HAVING COUNT(purchase_amount) > 50
ORDER BY SUM(purchase_amount) DESC
LIMIT 3;

-- q2. which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount,
       ROUND(AVG(purchase_amount) OVER (),2) AS avg_purchase,
       ROUND(purchase_amount - AVG(purchase_amount) OVER (),2) AS diff_from_avg,
       CASE
           WHEN purchase_amount > AVG(purchase_amount) OVER ()
           THEN 'Above Average'
           ELSE 'Below Average'
       END AS spending_category
FROM customer
WHERE discount_applied = 'Yes'
ORDER BY purchase_amount DESC;

--How many customers made purchases above the average order value while using a discount?

SELECT COUNT(*) as customers_count
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >
      (SELECT AVG(purchase_amount) FROM customer);

-- q3. which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) 
from customer 
group by item_purchased 
order by avg(review_rating) desc limit 5;-- learn typecast in sql 

-- q4. compare the average purchase amounts between standard and express shipping.

SELECT shipping_type, AVG(purchase_amount) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- q5.Do subscribed customers spend more? 
--compare average spend and total revenue between subscribers and non-subscribers?
 SELECT subscription_status, 
       count(customer_id) as total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend, 
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue desc, avg_spend DESC;

-- q6. which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(avg(case when discount_applied='Yes' then 1 else 0 end)*100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

-- q7. segment customers into new, returning, and loyal based on their total number of previous purchases, 
--and show the count of each segment.

with customer_type as(
select customer_id, previous_purchases,
case
   when previous_purchases=1 then 'New'
   when previous_purchases BETWEEN 2 and 10 then 'Returning'
   else 'Loyal'
   end as customer_segment
 from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- q8. what are the top 3 most purchased products within each category?
with item_counts as(
  select category, 
  item_purchased, 
  count(customer_id) as total_orders,
  ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

-- q9. Are customers who are repeat buyers(more than 5 previous purchases)also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

-- q10. what is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
--------------------------------------------------------------------------------------------


